/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\shmilysw\\blog\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\shmilysw\\blog\\node_modules\\vuepress-plugin-nprogress\\lib\\clientRootMixin.js"
import m2 from "D:\\shmilysw\\blog\\node_modules\\vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"
import m3 from "D:\\shmilysw\\blog\\node_modules\\@maginapp\\vuepress-plugin-katex\\clientRootMixin.js"
import m4 from "D:\\shmilysw\\blog\\node_modules\\vuepress-plugin-code-copy\\clientRootMixin.js"
import m5 from "D:\\shmilysw\\blog\\node_modules\\vuepress-plugin-zooming\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5
]