/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\shmilysw\\blog\\node_modules\\vuepress-theme-meteorlxy\\lib\\layouts\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-469e4aca",
    path: "/Projects/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Page", "v-469e4aca").then(next)
    },
  },
  {
    path: "/Projects/index.html",
    redirect: "/Projects/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Home", "v-b2754d56").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-be505a2e",
    path: "/posts/2023/03/25/git-github%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-be505a2e").then(next)
    },
  },
  {
    path: "/posts/2023/03/25/git-github入门.html",
    redirect: "/posts/2023/03/25/git-github%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/_posts/Git/Git-Github入门.html",
    redirect: "/posts/2023/03/25/git-github%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-3bba8da4",
    path: "/posts/2022/08/14/linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-3bba8da4").then(next)
    },
  },
  {
    path: "/posts/2022/08/14/linux常用命令.html",
    redirect: "/posts/2022/08/14/linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/_posts/Linux/Linux基础/Linux常用命令.html",
    redirect: "/posts/2022/08/14/linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    name: "v-d2753ba4",
    path: "/posts/2022/08/15/leetcode-2376-%E7%BB%9F%E8%AE%A1%E7%89%B9%E6%AE%8A%E6%95%B4%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-d2753ba4").then(next)
    },
  },
  {
    path: "/posts/2022/08/15/leetcode-2376-统计特殊整数.html",
    redirect: "/posts/2022/08/15/leetcode-2376-%E7%BB%9F%E8%AE%A1%E7%89%B9%E6%AE%8A%E6%95%B4%E6%95%B0.html"
  },
  {
    path: "/_posts/LeetCode刷题/数位dp/LeetCode-2376. 统计特殊整数.html",
    redirect: "/posts/2022/08/15/leetcode-2376-%E7%BB%9F%E8%AE%A1%E7%89%B9%E6%AE%8A%E6%95%B4%E6%95%B0.html"
  },
  {
    name: "v-7b0524ee",
    path: "/posts/2022/10/18/%E6%B5%85%E5%AD%A6javascript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7b0524ee").then(next)
    },
  },
  {
    path: "/posts/2022/10/18/浅学javascript.html",
    redirect: "/posts/2022/10/18/%E6%B5%85%E5%AD%A6javascript.html"
  },
  {
    path: "/_posts/Javascript/浅学JavaScript.html",
    redirect: "/posts/2022/10/18/%E6%B5%85%E5%AD%A6javascript.html"
  },
  {
    name: "v-f01ebae2",
    path: "/posts/2023/07/16/web%E5%89%8D%E7%AB%AF-%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-f01ebae2").then(next)
    },
  },
  {
    path: "/posts/2023/07/16/web前端-事件循环.html",
    redirect: "/posts/2023/07/16/web%E5%89%8D%E7%AB%AF-%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.html"
  },
  {
    path: "/_posts/WEB/WEB前端-事件循环.html",
    redirect: "/posts/2023/07/16/web%E5%89%8D%E7%AB%AF-%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.html"
  },
  {
    name: "v-437a78b8",
    path: "/posts/2023/09/04/%E9%93%B6%E8%A1%8C%E5%8D%A1%E8%AF%86%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-437a78b8").then(next)
    },
  },
  {
    path: "/posts/2023/09/04/银行卡识别.html",
    redirect: "/posts/2023/09/04/%E9%93%B6%E8%A1%8C%E5%8D%A1%E8%AF%86%E5%88%AB.html"
  },
  {
    path: "/_posts/Python/银行卡识别.html",
    redirect: "/posts/2023/09/04/%E9%93%B6%E8%A1%8C%E5%8D%A1%E8%AF%86%E5%88%AB.html"
  },
  {
    name: "v-2f6b44b6",
    path: "/posts/2023/07/06/%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93dll.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-2f6b44b6").then(next)
    },
  },
  {
    path: "/posts/2023/07/06/动态链接库dll.html",
    redirect: "/posts/2023/07/06/%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93dll.html"
  },
  {
    path: "/_posts/编程思维/动态链接库DLL.html",
    redirect: "/posts/2023/07/06/%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93dll.html"
  },
  {
    name: "v-6ef7186e",
    path: "/posts/2023/04/29/_00shell%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95-bash.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6ef7186e").then(next)
    },
  },
  {
    path: "/posts/2023/04/29/_00shell基础语法-bash.html",
    redirect: "/posts/2023/04/29/_00shell%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95-bash.html"
  },
  {
    path: "/_posts/Linux/shell/00shell基础语法_Bash.html",
    redirect: "/posts/2023/04/29/_00shell%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95-bash.html"
  },
  {
    name: "v-b2a94cee",
    path: "/posts/2023/05/06/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84-%E9%A9%AC%E4%B8%81%E5%BC%97%E5%8B%92.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-b2a94cee").then(next)
    },
  },
  {
    path: "/posts/2023/05/06/微服务架构-马丁弗勒.html",
    redirect: "/posts/2023/05/06/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84-%E9%A9%AC%E4%B8%81%E5%BC%97%E5%8B%92.html"
  },
  {
    path: "/_posts/设计模式/微服务架构-马丁弗勒.html",
    redirect: "/posts/2023/05/06/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84-%E9%A9%AC%E4%B8%81%E5%BC%97%E5%8B%92.html"
  },
  {
    name: "v-0d890a3b",
    path: "/posts/2023/07/11/c-%E4%B8%89%E5%B1%82-bll-dal-model-%E6%9E%B6%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-0d890a3b").then(next)
    },
  },
  {
    path: "/posts/2023/07/11/c-三层-bll-dal-model-架构.html",
    redirect: "/posts/2023/07/11/c-%E4%B8%89%E5%B1%82-bll-dal-model-%E6%9E%B6%E6%9E%84.html"
  },
  {
    path: "/_posts/设计模式/C#_三层（BLL DAL Model）架构.html",
    redirect: "/posts/2023/07/11/c-%E4%B8%89%E5%B1%82-bll-dal-model-%E6%9E%B6%E6%9E%84.html"
  },
  {
    name: "v-2aa314de",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("AboutLayout", "v-2aa314de").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-1f814451",
    path: "/posts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Posts", "v-1f814451").then(next)
    },
  },
  {
    path: "/posts/index.html",
    redirect: "/posts/"
  },
  {
    name: "v-03721585",
    path: "/posts/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-03721585").then(next)
    },
  },
  {
    path: "/posts/tags/index.html",
    redirect: "/posts/tags/"
  },
  {
    name: "v-5eb9e6bc",
    path: "/posts/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Categories", "v-5eb9e6bc").then(next)
    },
  },
  {
    path: "/posts/categories/index.html",
    redirect: "/posts/categories/"
  },
  {
    name: "v-5ccd84cc",
    path: "/posts/tags/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5ccd84cc").then(next)
    },
    meta: {"tagName":"git"}
  },
  {
    name: "v-b2125f9e",
    path: "/posts/tags/github.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b2125f9e").then(next)
    },
    meta: {"tagName":"github"}
  },
  {
    name: "v-2076106c",
    path: "/posts/tags/Linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2076106c").then(next)
    },
    meta: {"tagName":"Linux"}
  },
  {
    name: "v-23617cfc",
    path: "/posts/tags/操作系统.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-23617cfc").then(next)
    },
    meta: {"tagName":"操作系统"}
  },
  {
    name: "v-aec5c302",
    path: "/posts/tags/LeetCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-aec5c302").then(next)
    },
    meta: {"tagName":"LeetCode"}
  },
  {
    name: "v-094d32b2",
    path: "/posts/tags/数位dp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-094d32b2").then(next)
    },
    meta: {"tagName":"数位dp"}
  },
  {
    name: "v-d10719f8",
    path: "/posts/tags/算法.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d10719f8").then(next)
    },
    meta: {"tagName":"算法"}
  },
  {
    name: "v-493b3327",
    path: "/posts/tags/JavaScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-493b3327").then(next)
    },
    meta: {"tagName":"JavaScript"}
  },
  {
    name: "v-c58de496",
    path: "/posts/tags/编程语言学习.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c58de496").then(next)
    },
    meta: {"tagName":"编程语言学习"}
  },
  {
    name: "v-e37c3508",
    path: "/posts/tags/WEB前端开发.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e37c3508").then(next)
    },
    meta: {"tagName":"WEB前端开发"}
  },
  {
    name: "v-e90081c0",
    path: "/posts/tags/OCR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e90081c0").then(next)
    },
    meta: {"tagName":"OCR"}
  },
  {
    name: "v-1b43c396",
    path: "/posts/tags/图像识别.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1b43c396").then(next)
    },
    meta: {"tagName":"图像识别"}
  },
  {
    name: "v-08b4753d",
    path: "/posts/tags/编程思维.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-08b4753d").then(next)
    },
    meta: {"tagName":"编程思维"}
  },
  {
    name: "v-423fec78",
    path: "/posts/tags/资源共享.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-423fec78").then(next)
    },
    meta: {"tagName":"资源共享"}
  },
  {
    name: "v-4d6adad2",
    path: "/posts/tags/shell 脚本.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4d6adad2").then(next)
    },
    meta: {"tagName":"shell 脚本"}
  },
  {
    name: "v-531d4c54",
    path: "/posts/tags/设计模式.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-531d4c54").then(next)
    },
    meta: {"tagName":"设计模式"}
  },
  {
    path: '*',
    component: GlobalLayout
  }
]