/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Shmilysw",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "property": "og:url",
        "content": "https://Shmilysw.github.io"
      }
    ],
    [
      "meta",
      {
        "property": "og:site_name",
        "content": "Shmilysw's blog"
      }
    ],
    [
      "meta",
      {
        "property": "og:description",
        "content": "Shmilysw's blog"
      }
    ],
    [
      "meta",
      {
        "property": "og:title",
        "content": "Shmilysw's blog"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#222222"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/favicon.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/icons/favicon.png",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/favicon.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "git-github的入门",
      "frontmatter": {
        "title": "git-github的入门",
        "date": "2023-03-25T00:00:00.000Z",
        "tags": [
          "git",
          "github"
        ],
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false,
        "readingShow": "top"
      },
      "regularPath": "/_posts/Git/Git-Github%E5%85%A5%E9%97%A8.html",
      "relativePath": "_posts/Git/Git-Github入门.md",
      "key": "v-be505a2e",
      "path": "/posts/2023/03/25/git-github%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "git-github入门",
          "slug": "git-github入门"
        },
        {
          "level": 3,
          "title": "1. git介绍",
          "slug": "_1-git介绍"
        },
        {
          "level": 3,
          "title": "2. 演示ssh连接github",
          "slug": "_2-演示ssh连接github"
        },
        {
          "level": 3,
          "title": "3. 演示git的基本操作",
          "slug": "_3-演示git的基本操作"
        },
        {
          "level": 3,
          "title": "4. git的使用技巧（遇到的错误）",
          "slug": "_4-git的使用技巧-遇到的错误"
        },
        {
          "level": 3,
          "title": "5. github的基本介绍",
          "slug": "_5-github的基本介绍"
        }
      ],
      "type": "post",
      "top": false,
      "tags": [
        "git",
        "github"
      ],
      "createdAt": "2023-03-25",
      "updatedAt": null,
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "Shmilysw.github.io",
        "layout": "Home",
        "readingShow": "top"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/",
      "type": "page",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "layout": "Page",
        "readingShow": "top"
      },
      "regularPath": "/Projects/",
      "relativePath": "Projects/index.md",
      "key": "v-469e4aca",
      "path": "/Projects/",
      "type": "page",
      "codeSwitcherOptions": {}
    },
    {
      "title": "LeetCode 2376. 统计特殊整数",
      "frontmatter": {
        "title": "LeetCode 2376. 统计特殊整数",
        "date": "2022-8-15",
        "tags": [
          "LeetCode",
          "数位dp",
          "算法"
        ],
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false,
        "readingShow": "top"
      },
      "regularPath": "/_posts/LeetCode%E5%88%B7%E9%A2%98/%E6%95%B0%E4%BD%8Ddp/LeetCode-2376.%20%E7%BB%9F%E8%AE%A1%E7%89%B9%E6%AE%8A%E6%95%B4%E6%95%B0.html",
      "relativePath": "_posts/LeetCode刷题/数位dp/LeetCode-2376. 统计特殊整数.md",
      "key": "v-d2753ba4",
      "path": "/posts/2022/08/15/leetcode-2376-%E7%BB%9F%E8%AE%A1%E7%89%B9%E6%AE%8A%E6%95%B4%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "数位DP | 暴力 | 模板",
          "slug": "数位dp-暴力-模板"
        },
        {
          "level": 3,
          "title": "原题连接",
          "slug": "原题连接"
        },
        {
          "level": 3,
          "title": "题目:",
          "slug": "题目"
        },
        {
          "level": 3,
          "title": "方法一：",
          "slug": "方法一"
        },
        {
          "level": 3,
          "title": "方法二：",
          "slug": "方法二"
        }
      ],
      "type": "post",
      "top": false,
      "tags": [
        "LeetCode",
        "数位dp",
        "算法"
      ],
      "createdAt": "2022-08-15",
      "updatedAt": null,
      "codeSwitcherOptions": {}
    },
    {
      "title": "浅学JavaScript",
      "frontmatter": {
        "title": "浅学JavaScript",
        "date": "2022-10-18T00:00:00.000Z",
        "tags": [
          "JavaScript",
          "编程语言学习"
        ],
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false,
        "readingShow": "top"
      },
      "regularPath": "/_posts/Javascript/%E6%B5%85%E5%AD%A6JavaScript.html",
      "relativePath": "_posts/Javascript/浅学JavaScript.md",
      "key": "v-7b0524ee",
      "path": "/posts/2022/10/18/%E6%B5%85%E5%AD%A6javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "1、什么是JavaScript?",
          "slug": "_1、什么是javascript"
        },
        {
          "level": 3,
          "title": "1.1、概述",
          "slug": "_1-1、概述"
        },
        {
          "level": 3,
          "title": "1.2、历史",
          "slug": "_1-2、历史"
        },
        {
          "level": 3,
          "title": "1.3、 大前端开发",
          "slug": "_1-3、-大前端开发"
        },
        {
          "level": 2,
          "title": "2、快速入门",
          "slug": "_2、快速入门"
        },
        {
          "level": 3,
          "title": "2.1、引入JavaScript",
          "slug": "_2-1、引入javascript"
        },
        {
          "level": 3,
          "title": "2.2、浏览器调试",
          "slug": "_2-2、浏览器调试"
        },
        {
          "level": 3,
          "title": "2.3、严格模式",
          "slug": "_2-3、严格模式"
        },
        {
          "level": 2,
          "title": "3、数据类型",
          "slug": "_3、数据类型"
        },
        {
          "level": 3,
          "title": "3.1、字符串",
          "slug": "_3-1、字符串"
        },
        {
          "level": 3,
          "title": "3.2、数组",
          "slug": "_3-2、数组"
        },
        {
          "level": 3,
          "title": "3.3、对象",
          "slug": "_3-3、对象"
        },
        {
          "level": 3,
          "title": "3.4、流程控制",
          "slug": "_3-4、流程控制"
        },
        {
          "level": 3,
          "title": "3.5、Map和Set",
          "slug": "_3-5、map和set"
        },
        {
          "level": 3,
          "title": "3.6、iterator(迭代器)",
          "slug": "_3-6、iterator-迭代器"
        },
        {
          "level": 2,
          "title": "4、函数",
          "slug": "_4、函数"
        },
        {
          "level": 3,
          "title": "4.1、定义函数",
          "slug": "_4-1、定义函数"
        },
        {
          "level": 3,
          "title": "4.2、变量的作用域",
          "slug": "_4-2、变量的作用域"
        },
        {
          "level": 3,
          "title": "4.3、方法",
          "slug": "_4-3、方法"
        },
        {
          "level": 2,
          "title": "5、内部对象",
          "slug": "_5、内部对象"
        },
        {
          "level": 3,
          "title": "5.1、Date",
          "slug": "_5-1、date"
        },
        {
          "level": 3,
          "title": "5.2、JSON",
          "slug": "_5-2、json"
        },
        {
          "level": 3,
          "title": "5.3、Ajax",
          "slug": "_5-3、ajax"
        },
        {
          "level": 2,
          "title": "6、面向对象编程",
          "slug": "_6、面向对象编程"
        },
        {
          "level": 2,
          "title": "7、操作BOM对象(重点)",
          "slug": "_7、操作bom对象-重点"
        },
        {
          "level": 2,
          "title": "8、操作DOM对象(重点)",
          "slug": "_8、操作dom对象-重点"
        },
        {
          "level": 2,
          "title": "9、操作表单 (验证)",
          "slug": "_9、操作表单-验证"
        },
        {
          "level": 3,
          "title": "9.1、按钮绑定",
          "slug": "_9-1、按钮绑定"
        },
        {
          "level": 3,
          "title": "9.2、表单绑定",
          "slug": "_9-2、表单绑定"
        },
        {
          "level": 2,
          "title": "10、jQuery",
          "slug": "_10、jquery"
        },
        {
          "level": 2,
          "title": "一些问题",
          "slug": "一些问题"
        },
        {
          "level": 3,
          "title": "箭头函数的this",
          "slug": "箭头函数的this"
        }
      ],
      "type": "post",
      "top": false,
      "tags": [
        "JavaScript",
        "编程语言学习"
      ],
      "createdAt": "2022-10-18",
      "updatedAt": null,
      "codeSwitcherOptions": {}
    },
    {
      "title": "Linux 常用命令",
      "frontmatter": {
        "title": "Linux 常用命令",
        "date": "2022-8-14",
        "tags": [
          "Linux",
          "操作系统"
        ],
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false,
        "readingShow": "top"
      },
      "regularPath": "/_posts/Linux/Linux%E5%9F%BA%E7%A1%80/Linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "relativePath": "_posts/Linux/Linux基础/Linux常用命令.md",
      "key": "v-3bba8da4",
      "path": "/posts/2022/08/14/linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "headers": [
        {
          "level": 2,
          "title": "Linux 常用命令",
          "slug": "linux-常用命令"
        },
        {
          "level": 3,
          "title": "主要内容来源：",
          "slug": "主要内容来源"
        },
        {
          "level": 3,
          "title": "常用命令介绍(y总总结)",
          "slug": "常用命令介绍-y总总结"
        },
        {
          "level": 3,
          "title": "自己总结",
          "slug": "自己总结"
        }
      ],
      "type": "post",
      "top": false,
      "tags": [
        "Linux",
        "操作系统"
      ],
      "createdAt": "2022-08-14",
      "updatedAt": null,
      "codeSwitcherOptions": {}
    },
    {
      "title": "Shmilysw",
      "frontmatter": {
        "layout": "AboutLayout",
        "title": "Shmilysw",
        "readingShow": "top"
      },
      "regularPath": "/about/",
      "relativePath": "about/index.md",
      "key": "v-2aa314de",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "大家好，这里是Shmilysw！怎么感觉我是在这里写日记，哈哈！",
          "slug": "大家好-这里是shmilysw-怎么感觉我是在这里写日记-哈哈"
        },
        {
          "level": 2,
          "title": "个人简介：",
          "slug": "个人简介"
        },
        {
          "level": 2,
          "title": "目前状态：",
          "slug": "目前状态"
        },
        {
          "level": 2,
          "title": "未来规划：",
          "slug": "未来规划"
        },
        {
          "level": 2,
          "title": "浅浅的学习了的技术：",
          "slug": "浅浅的学习了的技术"
        },
        {
          "level": 2,
          "title": "学习历程",
          "slug": "学习历程"
        }
      ],
      "type": "page",
      "codeSwitcherOptions": {}
    },
    {
      "title": "shell 基础语法 (bash)",
      "frontmatter": {
        "title": "shell 基础语法 (bash)",
        "date": "2023-04-29T00:00:00.000Z",
        "tags": [
          "shell 脚本"
        ],
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false,
        "readingShow": "top"
      },
      "regularPath": "/_posts/Linux/shell/00shell%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95_Bash.html",
      "relativePath": "_posts/Linux/shell/00shell基础语法_Bash.md",
      "key": "v-6ef7186e",
      "path": "/posts/2023/04/29/_00shell%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95-bash.html",
      "headers": [
        {
          "level": 2,
          "title": "执行",
          "slug": "执行"
        },
        {
          "level": 3,
          "title": "用解释器执行：",
          "slug": "用解释器执行"
        },
        {
          "level": 2,
          "title": "注释",
          "slug": "注释"
        },
        {
          "level": 2,
          "title": "变量",
          "slug": "变量"
        },
        {
          "level": 3,
          "title": "定义变量",
          "slug": "定义变量"
        },
        {
          "level": 3,
          "title": "使用变量",
          "slug": "使用变量"
        },
        {
          "level": 3,
          "title": "只读变量",
          "slug": "只读变量"
        },
        {
          "level": 3,
          "title": "删除变量",
          "slug": "删除变量"
        },
        {
          "level": 3,
          "title": "变量类型",
          "slug": "变量类型"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 3,
          "title": "获取字符串长度",
          "slug": "获取字符串长度"
        },
        {
          "level": 2,
          "title": "默认变量",
          "slug": "默认变量"
        },
        {
          "level": 3,
          "title": "其他参数相关的变量",
          "slug": "其他参数相关的变量"
        },
        {
          "level": 2,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "定义",
          "slug": "定义"
        },
        {
          "level": 3,
          "title": "读取数组中某个元素的值",
          "slug": "读取数组中某个元素的值"
        },
        {
          "level": 3,
          "title": "读取整个数组",
          "slug": "读取整个数组"
        },
        {
          "level": 3,
          "title": "读取数组长度",
          "slug": "读取数组长度"
        },
        {
          "level": 2,
          "title": "if…then 语句",
          "slug": "if-then-语句"
        },
        {
          "level": 3,
          "title": "单层 if-else",
          "slug": "单层-if-else"
        },
        {
          "level": 3,
          "title": "多层 if-elif-elif-else",
          "slug": "多层-if-elif-elif-else"
        },
        {
          "level": 3,
          "title": "case…esac 形式",
          "slug": "case-esac-形式"
        },
        {
          "level": 2,
          "title": "for…in…do…done",
          "slug": "for-in-do-done"
        },
        {
          "level": 3,
          "title": "while…do…done 循环",
          "slug": "while-do-done-循环"
        },
        {
          "level": 3,
          "title": "until…do…done 循环（和 while 的逻辑相反）",
          "slug": "until-do-done-循环-和-while-的逻辑相反"
        },
        {
          "level": 3,
          "title": "break 命令",
          "slug": "break-命令"
        },
        {
          "level": 3,
          "title": "continue 命令",
          "slug": "continue-命令"
        },
        {
          "level": 2,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 3,
          "title": "不获取 return 值和 stdout 值",
          "slug": "不获取-return-值和-stdout-值"
        },
        {
          "level": 3,
          "title": "获取 return 值和 stdout 值",
          "slug": "获取-return-值和-stdout-值"
        },
        {
          "level": 3,
          "title": "函数的输入参数",
          "slug": "函数的输入参数"
        },
        {
          "level": 3,
          "title": "函数内的局部变量",
          "slug": "函数内的局部变量"
        }
      ],
      "type": "post",
      "top": false,
      "tags": [
        "shell 脚本"
      ],
      "createdAt": "2023-04-29",
      "updatedAt": null,
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "Posts",
        "layout": "Posts",
        "readingShow": "top"
      },
      "regularPath": "/posts/",
      "key": "v-1f814451",
      "path": "/posts/",
      "type": "page",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/",
      "key": "v-03721585",
      "path": "/posts/tags/",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "Categories",
        "layout": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/posts/categories/",
      "key": "v-5eb9e6bc",
      "path": "/posts/categories/",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "git | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/git.html",
      "key": "v-5ccd84cc",
      "path": "/posts/tags/git.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "github | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/github.html",
      "key": "v-b2125f9e",
      "path": "/posts/tags/github.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "LeetCode | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/LeetCode.html",
      "key": "v-aec5c302",
      "path": "/posts/tags/LeetCode.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "数位dp | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/%E6%95%B0%E4%BD%8Ddp.html",
      "key": "v-094d32b2",
      "path": "/posts/tags/数位dp.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "算法 | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/%E7%AE%97%E6%B3%95.html",
      "key": "v-d10719f8",
      "path": "/posts/tags/算法.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "JavaScript | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/JavaScript.html",
      "key": "v-493b3327",
      "path": "/posts/tags/JavaScript.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "编程语言学习 | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%AD%A6%E4%B9%A0.html",
      "key": "v-c58de496",
      "path": "/posts/tags/编程语言学习.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "Linux | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/Linux.html",
      "key": "v-2076106c",
      "path": "/posts/tags/Linux.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "操作系统 | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.html",
      "key": "v-23617cfc",
      "path": "/posts/tags/操作系统.html",
      "codeSwitcherOptions": {}
    },
    {
      "frontmatter": {
        "title": "shell 脚本 | Tag",
        "layout": "Tag",
        "readingShow": "top"
      },
      "regularPath": "/posts/tags/shell%20%E8%84%9A%E6%9C%AC.html",
      "key": "v-4d6adad2",
      "path": "/posts/tags/shell 脚本.html",
      "codeSwitcherOptions": {}
    }
  ],
  "themeConfig": {
    "markdown": {
      "enableAll": true
    },
    "locales": {
      "/": {
        "lang": "en-US"
      }
    },
    "lastUpdated": true,
    "lang": {
      "home": "Shmilysw.github.io",
      "posts": "Posts",
      "category": "Category",
      "categories": "Categories",
      "tag": "Tag",
      "tags": "Tags",
      "allCategories": "All",
      "search": "Search",
      "searchHint": "Search in title and excerpt",
      "noRelatedPosts": "No related posts",
      "top": "Top",
      "createdAt": "Created",
      "updatedAt": "Updated",
      "prevPost": "Previous Post",
      "nextPost": "Next Post",
      "toc": "Table of Contents",
      "comments": "Comments",
      "notFound": "Oops ! The page is not here"
    },
    "pagination": {
      "perPage": 10
    },
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "exact": true
      },
      {
        "text": "Posts",
        "link": "/posts/",
        "exact": false
      },
      {
        "text": "About",
        "link": "/about/",
        "exact": false
      }
    ],
    "personalInfo": {
      "nickname": "shi'wei",
      "description": "Waiting for love.",
      "email": "shmilysw2002@163.com",
      "location": "Tai'Zhou, Zhe'Jiang, China",
      "organization": "Tai'Zhou University",
      "avatar": "https://cdn.acwing.com/media/user/profile/photo/120382_lg_2ec963416b.jpg",
      "sns": {
        "github": {
          "account": "Shmilysw",
          "link": "https://github.com/Shmilysw"
        }
      }
    },
    "header": {
      "background": {
        "useGeo": false,
        "url": "https://s2.loli.net/2022/02/16/pa8cMOXlbjYABTI.png"
      },
      "showTitle": true
    },
    "footer": {
      "poweredBy": false,
      "poweredByTheme": false
    },
    "infoCard": {
      "headerBackground": {
        "url": "https://cdn.acwing.com/media/article/image/2023/04/26/120382_b639cb7ce4-background9.png",
        "useGeo": true
      }
    },
    "comments": false,
    "defaultPages": {},
    "smoothScroll": true,
    "zooming": {}
  }
}