/**
 * Generated by "@vuepress/plugin-blog (meteorlxy modified version)"
 */
export default {
  "git": {
    "path": "/posts/tags/git.html",
    "pageKeys": [
      "v-be505a2e"
    ]
  },
  "github": {
    "path": "/posts/tags/github.html",
    "pageKeys": [
      "v-be505a2e"
    ]
  },
  "LeetCode": {
    "path": "/posts/tags/LeetCode.html",
    "pageKeys": [
      "v-d2753ba4"
    ]
  },
  "数位dp": {
    "path": "/posts/tags/数位dp.html",
    "pageKeys": [
      "v-d2753ba4"
    ]
  },
  "算法": {
    "path": "/posts/tags/算法.html",
    "pageKeys": [
      "v-d2753ba4"
    ]
  },
  "JavaScript": {
    "path": "/posts/tags/JavaScript.html",
    "pageKeys": [
      "v-7b0524ee"
    ]
  },
  "编程语言学习": {
    "path": "/posts/tags/编程语言学习.html",
    "pageKeys": [
      "v-7b0524ee"
    ]
  },
  "Linux": {
    "path": "/posts/tags/Linux.html",
    "pageKeys": [
      "v-3bba8da4"
    ]
  },
  "操作系统": {
    "path": "/posts/tags/操作系统.html",
    "pageKeys": [
      "v-3bba8da4"
    ]
  },
  "shell 脚本": {
    "path": "/posts/tags/shell 脚本.html",
    "pageKeys": [
      "v-6ef7186e"
    ]
  }
}